# Parameters of stage window
window_size: [500.0, 500.0]
window_center: [0.0, 0.0]
window_rotate: [0.0, 0.0]
window_scale: 13.660
show_data: true
show_grid: true
# Floor plan
map_name: empty
floor_size: [30.0, 30.0, 2.0]
# Robot
laser_pose: [0.4, 0.0, -0.2, 0.0]
number_of_robots: 5
